# Generated by Django 3.2.8 on 2021-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211102_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('employee', 'Employee')], default='member', max_length=16),
        ),
    ]
