# Generated by Django 3.2.8 on 2021-11-06 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('members', '0008_auto_20211106_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('single_class', models.BooleanField(default=False)),
                ('gender_type', models.CharField(choices=[(' male', 'Male'), ('female', 'Female'), ('not-specified', 'Not Specified')], default='not-specified', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default='1', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('limit', models.PositiveIntegerField(default=10)),
                ('available_seat', models.PositiveIntegerField()),
                ('attended_members', models.ManyToManyField(blank=True, null=True, related_name='attended_members', to='members.Member')),
                ('base_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_schedules', to='classes.baseclass')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='members', to='members.Member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainer_classes', to='hr.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='booked_classes', to='members.member')),
                ('scheduled_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_bookings', to='classes.classschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baseclass',
            name='weekday',
            field=models.ManyToManyField(to='classes.WeekDay'),
        ),
    ]
