# Generated by Django 3.2.8 on 2021-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
