# Generated by Django 3.2.8 on 2021-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classschedule_postpone_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseclass',
            name='weekday',
            field=models.ManyToManyField(blank=True, null=True, to='classes.WeekDay'),
        ),
    ]
