# Generated by Django 3.2.8 on 2021-11-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_weekday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='attended_members',
        ),
    ]
