# Generated by Django 3.2.8 on 2021-11-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0010_auto_20211109_0715'),
        ('classes', '0007_alter_weekday_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gym_attendances', to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uom', models.CharField(choices=[('count', 'Count')], default='count', max_length=8)),
                ('base_amount', models.FloatField(default=1)),
                ('reduce_calorie', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GymWorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1)),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workouts_for_gym', to='attendances.workouttype')),
                ('gym_attendance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gym_workouts', to='attendances.gymattendance')),
            ],
        ),
        migrations.CreateModel(
            name='ClassWorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1)),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workouts_for_classes', to='attendances.workouttype')),
                ('class_attendance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_workouts', to='classes.classschedule')),
            ],
        ),
    ]
