# Generated by Django 3.2.8 on 2021-11-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkOutType',
            new_name='WorkOut',
        ),
    ]
