# Generated by Django 3.2.8 on 2021-11-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('attendances', '0002_rename_workouttype_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='uom',
            field=models.CharField(choices=[('count', 'Count'), ('kg', 'Kg')], default='count', max_length=8),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_attendances', to='hr.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
