# Generated by Django 3.2.8 on 2021-11-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_weekday_day'),
        ('attendances', '0004_alter_gymworkout_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classworkout',
            unique_together={('class_attendance', 'base_type')},
        ),
    ]
