# Generated by Django 3.2.8 on 2021-11-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_remove_classschedule_attended_members'),
        ('attendances', '0007_auto_20211115_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='class_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_attendance', to='classes.classschedule'),
        ),
    ]
