# Generated by Django 3.2.8 on 2021-11-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID_card', models.CharField(blank=True, max_length=64, null=True)),
                ('biometric_id', models.CharField(blank=True, max_length=64, null=True)),
                ('designation', models.CharField(choices=[('trainer', 'Trainer'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('Employee', 'Employee')], default='Employee', max_length=16)),
                ('total_salary', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('hourly_salary', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
