# Generated by Django 3.2.8 on 2021-11-02 06:18

import django.db.models.deletion
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('uom', models.CharField(max_length=128)),
                ('base_amount', models.FloatField(default=1)),
                ('base_in_calorie', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID_card', models.CharField(blank=True, max_length=64, null=True)),
                ('biometric_id', models.CharField(blank=True, max_length=64, null=True)),
                ('medical_issues', models.JSONField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=16, null=True)),
                ('neck', models.CharField(blank=True, max_length=16, null=True)),
                ('chest', models.CharField(blank=True, max_length=16, null=True)),
                ('left_arm', models.CharField(blank=True, max_length=16, null=True)),
                ('right_arm', models.CharField(blank=True, max_length=16, null=True)),
                ('waist', models.CharField(blank=True, max_length=16, null=True)),
                ('hips', models.CharField(blank=True, max_length=16, null=True)),
                ('left_thigh', models.CharField(blank=True, max_length=16, null=True)),
                ('right_thigh', models.CharField(blank=True, max_length=16, null=True)),
                ('left_calf', models.CharField(blank=True, max_length=16, null=True)),
                ('right_calf', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.CharField(blank=True, max_length=16, null=True)),
                ('allergy_foods', models.ManyToManyField(to='members.Food')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans_added', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nutrition_plans', to='members.member')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackNutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='nutrition_plans/2021-11-02/', verbose_name='ProfilePicture')),
                ('checked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.nutritionplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrackBodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='body_measurements/2021-11-02/', verbose_name='ProfilePicture')),
                ('height', models.CharField(max_length=16)),
                ('neck', models.CharField(max_length=16)),
                ('chest', models.CharField(max_length=16)),
                ('left_arm', models.CharField(max_length=16)),
                ('right_arm', models.CharField(max_length=16)),
                ('waist', models.CharField(max_length=16)),
                ('hips', models.CharField(max_length=16)),
                ('left_thigh', models.CharField(max_length=16)),
                ('right_thigh', models.CharField(max_length=16)),
                ('left_calf', models.CharField(max_length=16)),
                ('right_calf', models.CharField(max_length=16)),
                ('weight', models.CharField(max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='body_measurements_tracking', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='FoodToEat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_foods', to='members.food')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.nutritionplan')),
            ],
        ),
        migrations.CreateModel(
            name='FoodsConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_foods', to='members.food')),
                ('plan_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.tracknutritionplan')),
            ],
        ),
    ]
