# Generated by Django 3.2.8 on 2021-11-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_auto_20211103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='allergy_foods',
            field=models.ManyToManyField(blank=True, null=True, to='members.Food'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_info', to='users.user'),
            preserve_default=False,
        ),
    ]
