# Generated by Django 3.2.8 on 2021-11-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20211104_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackbodymeasurement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='foodsconsumed',
            unique_together={('plan_track', 'food')},
        ),
        migrations.AlterUniqueTogether(
            name='foodtoeat',
            unique_together={('plan', 'food')},
        ),
    ]
