# Generated by Django 3.2.8 on 2021-11-14 05:54

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20211109_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackbodymeasurement',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='body_measurements/2021-11-14/', verbose_name='ProfilePicture'),
        ),
        migrations.AlterField(
            model_name='tracknutritionplan',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='nutrition_plans/2021-11-14/', verbose_name='ProfilePicture'),
        ),
    ]
